name: Kotlin Linter
on: push

jobs:
   ktlint:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v4.2.2

       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v1"